[package]
name = "07_voice"
version = "0.1.0"
authors = ["my name <my@email.address>"]

[dependencies.serenity]
features = ["cache", "framework", "methods", "voice"]
# version = "0.1"
path = "../../"
