parameters:
  name: ''
  vmImage: ''
  toolchain: 'stable'
  features: 'all'

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    toolchain: ${{ parameters.toolchain }}
    features: ${{ parameters.features }}
  steps:
  - powershell: |
      Invoke-WebRequest -Uri "https://win.rustup.rs" -OutFile "rustup-init.exe"
      &".\rustup-init.exe" --default-toolchain $(toolchain) -y
    displayName: 'Install rust'
  - powershell: |
      If ("$(features)" -eq "all") {
        cargo build --all-features
      }
      Else {
        cargo build --no-default-features --features "$(features)"
      }
    displayName: 'Build Serenity'
  - powershell: |
      If ("$(features)" -eq "all") {
        cargo test --all-features
      }
      Else {
        cargo test --no-default-features --features "$(features)"
      }
    displayName: 'Test Serenity'
