parameters:
  name: ''
  vmImage: ''
  toolchain: 'stable'
  features: 'all'

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    tc: ${{ parameters.toolchain }}
    os: ${{ parameters.vmImage }}
    features: ${{ parameters.features }}
  steps:
  - bash: |
      if [[ "$OS" == "macOS-latest" ]]; then
        HOMEBREW_NO_AUTO_UPDATE=1 brew install automake autoconf libtool libsodium pkg-config
      fi
      if [[ "$OS" == "ubuntu-latest" ]]; then
        sudo apt-get install -y libsodium-dev libssl-dev
      fi
    displayName: 'Install dependencies'

  - bash: |
      curl -o rustup-init.sh https://sh.rustup.rs -sSf
      sh rustup-init.sh --default-toolchain $(tc) -y
    displayName: 'Install Rust'

  - bash: |
      source $HOME/.cargo/env
      cd examples/
      cargo build -p e01_basic_ping_bot
    displayName: 'Build example 1'

  - bash: |
      source $HOME/.cargo/env
      cd examples/
      cargo build -p e02_transparent_guild_sharding
    displayName: 'Build example 2'

  - bash: |
      source $HOME/.cargo/env
      cd examples/
      cargo build -p e03_struct_utilities
    displayName: 'Build example 3'

  - bash: |
      source $HOME/.cargo/env
      cd examples/
      cargo build -p e04_message_builder
    displayName: 'Build example 4'

  - bash: |
      source $HOME/.cargo/env
      cd examples/
      cargo build -p e05_command_framework
    displayName: 'Build example 5'

  - bash: |
      source $HOME/.cargo/env
      cd examples/
      cargo build -p e06_voice
    displayName: 'Build example 6'

  - bash: |
      source $HOME/.cargo/env
      cd examples/
      cargo build -p e07_sample_bot_structure
    displayName: 'Build example 7'

  - bash: |
      source $HOME/.cargo/env
      cd examples/
      cargo build -p e08_env_logging
    displayName: 'Build example 8'

  - bash: |
      source $HOME/.cargo/env
      cd examples/
      cargo build -p e09_shard_manager
    displayName: 'Build example 9'

  - bash: |
      source $HOME/.cargo/env
      cd examples/
      cargo build -p e10_voice_receive
    displayName: 'Build example 10'

  - bash: |
      source $HOME/.cargo/env
      cd examples/
      cargo build -p e11_create_message_builder
    displayName: 'Build example 11'

  - bash: |
      source $HOME/.cargo/env
      cd examples/
      cargo build -p e12_collectors
    displayName: 'Build example 12'

  - bash: |
      source $HOME/.cargo/env
      cd examples/
      cargo build -p e13_gateway_intents
    displayName: 'Build example 13'

