[package]
name = "serenity"
version = "0.12.5"
authors = ["Alex M. M. <acdenissk69@gmail.com>"]
description = "A Rust library for the Discord API."
readme = "README.md"
include = ["src/**/*", "LICENSE.md", "README.md", "CHANGELOG.md", "build.rs"]

documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[workspace]
members = ["examples/*", "serenity-core"]

[workspace.package]
documentation = "https://docs.rs/serenity"
homepage = "https://github.com/serenity-rs/serenity"
repository = "https://github.com/serenity-rs/serenity.git"
keywords = ["discord", "api"]
license = "ISC"
edition = "2024"
rust-version = "1.95"

[workspace.dependencies]
aformat = "0.1.8"
dashmap = "6.1.0"
extract_map = { version = "0.3.1", features = ["serde"] }
futures = { version = "0.3.32", default-features = false, features = ["std"] }
parking_lot = "0.12.5"
reqwest = { version = ">=0.13", default-features = false, features = ["multipart", "stream", "json"] }
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = { version = "1.0.147", features = ["raw_value"] }
small-fixed-array = { version = "0.4.10", features = ["serde"] }
strum = { version = "0.27.2", features = ["derive"] }
to-arraystring = "0.2.2"
tokio = { version = "1.48.0", features = ["macros", "rt", "sync", "time", "io-util"] }
tracing = { version = "0.1.44", features = ["log"] }
typesize = { version = "0.1.14", features = ["url", "time", "serde_json", "secrecy", "parking_lot", "nonmax"] }
url = { version = "2.5.7", features = ["serde"] }

[dependencies]
# Serenity workspace crates
serenity-core = { path = "serenity-core" }

# Workspace dependencies
aformat = { workspace = true, optional = true }
dashmap = { workspace = true, optional = true }
extract_map = { workspace = true, optional = true }
futures = { workspace = true }
parking_lot = { workspace = true }
reqwest = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
small-fixed-array = { workspace = true }
strum = { workspace = true, optional = true }
to-arraystring = { workspace = true, optional = true }
tokio = { workspace = true }
tracing = { workspace = true, optional = true }
typesize = { workspace = true, optional = true }
url = { workspace = true, optional = true }

# Additional dependencies
async-trait = "0.1.89"
ed25519-dalek = { version = "2.2.0", optional = true }
flate2 = { version = "1.1.9", features = ["zlib-rs"], optional = true }
tokio-tungstenite = { version = "0.28.0", features = ["url"], optional = true }
zstd = { version = "0.13", default-features = false, optional = true }

[features]
# Defaults with different backends
default = ["default_no_backend", "rustls_backend"]
default_rustls_no_provider = ["default_no_backend", "rustls_backend_no_provider"]
default_native_tls = ["default_no_backend", "native_tls_backend"]

# Serenity requires a backend, this picks all default features without a backend.
default_no_backend = [
    "cache",
    "chrono",
    "framework",
    "transport_compression_zlib",
    "transport_compression_zstd",
]

# Enables builder structs to configure Discord HTTP requests. Without this feature, you have to
# construct JSON manually at some places.
builder = ["serenity-core/builder"]
# Enables the cache, which stores the data received from Discord gateway to provide access to
# complete guild data, channels, users and more without needing HTTP requests.
cache = ["serenity-core/cache"]
# Enables collectors, a utility feature that lets you await interaction events in code with
# zero setup, without needing to setup an InteractionCreate event listener.
collector = ["gateway", "to-arraystring"]
# Enables the Framework trait which is an abstraction for old-style text commands.
framework = ["gateway"]
# Enables gateway support, which allows bots to listen for Discord events.
gateway = [
    "model",
    "aformat",
    "extract_map",
    "flate2",
    "dashmap",
    "reqwest",
    "strum",
    "tracing",
    "url"
]
# Enables HTTP, which enables bots to execute actions on Discord.
http = ["serenity-core/http"]
# Enables wrapper methods around HTTP requests on model types.
# Requires "builder" to configure the requests and "http" to execute them.
# Note: the model type definitions themselves are always active, regardless of this feature.
# TODO: remove dependeny on utils feature
model = ["serenity-core/model", "builder", "http", "utils"]
# Enables zlib-stream transport compression of incoming gateway events.
transport_compression_zlib = ["flate2", "gateway"]
# Enables zstd-stream transport compression of incoming gateway events.
transport_compression_zstd = ["zstd", "gateway"]
# Enables support for Discord API functionality that's not stable yet, as well as serenity APIs that
# are allowed to change even in semver non-breaking updates.
unstable = ["serenity-core/unstable"]
# Enables some utility functions that can be useful for bot creators.
utils = ["serenity-core/utils"]
voice = ["gateway"]
# Enables unstable tokio features to give explicit names to internally spawned tokio tasks
tokio_task_builder = ["tokio/tracing", "serenity-core/tokio_task_builder"]
interactions_endpoint = ["ed25519-dalek"]
# Uses chrono for Timestamp, instead of time
chrono = ["serenity-core/chrono"]

# This enables all parts of the serenity codebase
# (Note: all feature-gated APIs to be documented should have their features listed here!)
#
# Unstable functionality should be gated under the `unstable` feature.
full = ["default", "collector", "voice", "interactions_endpoint"]

# Enables temporary caching in functions that retrieve data via the HTTP API.
temp_cache = ["serenity-core/temp_cache"]

typesize = ["dep:typesize", "serenity-core/typesize"]

# Enables compile-time heavy instrument macros from tracing
tracing_instrument = ["serenity-core/tracing_instrument", "tracing/attributes"]

# Backends to pick from:
# - Rustls Backends
rustls_backend = [
    "serenity-core/rustls_backend",
    "tokio-tungstenite/rustls-tls-webpki-roots",
]
rustls_backend_no_provider = [
    "serenity-core/rustls_backend_no_provider",
    "tokio-tungstenite/rustls-tls-webpki-roots",
]

# - Native TLS Backends
native_tls_backend = [
    "serenity-core/native_tls_backend",
    "tokio-tungstenite/native-tls",
]

[package.metadata.docs.rs]
features = ["full"]
rustdoc-args = ["--cfg", "docsrs"]
