//! Message bodies used in gateway event-handling.

use std::net::IpAddr;

use serde::{Deserialize, Serialize};

use crate::id::*;
use crate::protocol_data::ProtocolData;
use crate::speaking_state::SpeakingState;
use crate::util::json_safe_u64;

/// Message indicating that another user has connected to the voice channel.
///
/// Acts as a source of UserId+SSRC identification.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct ClientConnect {
    /// SSRC of any audio packets sent by this newly joined user.
    pub audio_ssrc: u32,
    /// ID of the connecting user.
    pub user_id: UserId,
    /// SSRC of any audio packets sent by this newly joined user.
    ///
    /// Bots should not see any packets with this SSRC.
    pub video_ssrc: u32,
}
/// Message indicating that another user has disconnected from the voice channel.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct ClientDisconnect {
    /// Id of the disconnected user.
    pub user_id: UserId,
}

/// List of user IDs currently in the voice channel.
#[derive(Clone, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct ClientsConnect {
    /// List of user IDs in the voice channel.
    pub user_ids: Vec<UserId>,
}

/// Video stream information (opcode 10, unused by bots).
#[derive(Clone, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct Video {
    /// SSRC for the video stream.
    #[serde(default)]
    pub audio_ssrc: u32,
    /// Video SSRC.
    #[serde(default)]
    pub video_ssrc: u32,
    /// User ID of the video sender.
    #[serde(default)]
    pub user_id: Option<UserId>,
}

/// Media sink wants update (opcode 14, unused by bots).
#[derive(Clone, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct MediaSinkWants {
    /// Any value - structure unknown.
    #[serde(default)]
    pub any: Option<u32>,
}

/// Voice backend version (opcode 15, unused by bots).
#[derive(Clone, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct VoiceBackendVersion {
    /// Voice backend version string.
    #[serde(default)]
    pub voice: String,
    /// RTC worker version string.
    #[serde(default)]
    pub rtc_worker: String,
}

/// Channel options update (opcode 16, unused by bots).
#[derive(Clone, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct ChannelOptionsUpdate {
    /// Any value - structure unknown.
    #[serde(default)]
    pub any: Option<u32>,
}

/// User flags in voice (muted, deafened, etc.).
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct Flags {
    /// User ID whose flags changed.
    pub user_id: UserId,
    /// Flags bitfield.
    pub flags: u32,
}

/// Platform information for a user.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct Platform {
    /// User ID.
    pub user_id: UserId,
    /// Platform code (0 = desktop, 1 = mobile, 2 = web, etc.).
    pub platform: u32,
}

/// Used to keep the websocket connection alive.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
#[serde(transparent)]
pub struct Heartbeat {
    /// Random number generated by the client, to be mirrored by the server.
    pub nonce: u64,
}

/// Heartbeat ACK, received by the client to show the server's receipt of a heartbeat.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
#[serde(transparent)]
pub struct HeartbeatAck {
    /// Random 64-bit number previously generated by the client, mirrored by the server.
    #[serde(with = "json_safe_u64")]
    pub nonce: u64,
}

/// Used to determine how often the client must send a heartbeat.
#[derive(Clone, Copy, Debug, Deserialize, Serialize)]
pub struct Hello {
    /// Number of milliseconds to wait between sending heartbeat messages.
    pub heartbeat_interval: f64,
}

/// Used to begin a voice websocket connection.
#[derive(Clone, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct Identify {
    /// GuildId which the target voice channel belongs to.
    pub server_id: GuildId,
    /// Authentication session received from Discord's main gateway as part of a
    /// `"VOICE_STATE_UPDATE"` message.
    pub session_id: String,
    /// Authentication token received from Discord's main gateway as part of a
    /// `"VOICE_SERVER_UPDATE"` message.
    pub token: String,
    /// UserId of the client who is connecting.
    pub user_id: UserId,
    /// Maximum DAVE protocol version supported by the client.
    ///
    /// Signals to Discord that the bot supports end-to-end encryption.
    /// If omitted, the client does not support DAVE.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_dave_protocol_version: Option<u16>,
}

/// RTP server's connection offer and supported encryption modes.
#[derive(Clone, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct Ready {
    /// IP address of the call's allocated RTP server.
    pub ip: IpAddr,
    /// Set of voice encryption modes offered by the server.
    pub modes: Vec<String>,
    /// Destination port on the call's allocated RTP server.
    pub port: u16,
    /// RTP synchronisation source assigned by the server to the client.
    pub ssrc: u32,
}

/// Sent by the client after a disconnect to attempt to resume a session.
#[derive(Clone, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct Resume {
    /// GuildId which the target voice channel belongs to.
    pub server_id: GuildId,
    /// Authentication session received from Discord's main gateway as part of a
    /// `"VOICE_STATE_UPDATE"` message.
    pub session_id: String,
    /// Authentication token received from Discord's main gateway as part of a
    /// `"VOICE_SERVER_UPDATE"` message.
    pub token: String,
}

/// Used to select the voice protocol and encryption mechanism.
#[derive(Clone, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct SelectProtocol {
    /// Client's response to encryption/connection negotiation.
    pub data: ProtocolData,
    /// Transport protocol.
    ///
    /// Currently, `"udp"` is the only known accepted value.
    pub protocol: String,
}

/// Server's confirmation of a negotiated encryption scheme.
#[derive(Clone, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct SessionDescription {
    /// The negotiated encryption mode.
    pub mode: String,
    /// Key used for encryption of RTP payloads using the chosen mode.
    pub secret_key: Vec<u8>,
    /// The DAVE protocol version used.
    pub dave_protocol_version: u16,
}

/// Used to indicate which users are speaking, or to inform Discord that the client is now
/// speaking.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct Speaking {
    /// Function currently unknown.
    ///
    /// Docs suggest setting to `Some(0)` when sending this message as a client.
    pub delay: Option<u32>,
    /// How/whether a user has started/stopped speaking.
    pub speaking: SpeakingState,
    /// RTP synchronisation source of the speaker.
    pub ssrc: u32,
    /// User ID of the speaker, included in messages *received from* the server.
    ///
    /// Used alongside the SSRC to map individual packets to their sender.
    pub user_id: Option<UserId>,
}

/// DAVE protocol version field in the Identify payload.
///
/// Signals to Discord that the bot supports end-to-end encryption
/// and which protocol version(s) it supports.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
#[serde(transparent)]
pub struct MaxDaveProtocolVersion(pub u16);

impl MaxDaveProtocolVersion {
    /// Protocol version 1 - Current DAVE protocol version
    pub const V1: Self = Self(1);
}

impl Default for MaxDaveProtocolVersion {
    fn default() -> Self {
        Self::V1
    }
}

/// External sender package for DAVE MLS group creation.
///
/// Received from the server (Opcode 25) containing the voice gateway's
/// credential and signature public key for the MLS group's external_senders extension.
///
/// **Note:** This opcode uses binary WebSocket frames, not JSON.
/// Binary format: `[opcode: u8][external_sender: Vec<u8>]`
#[derive(Clone, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct DaveMlsExternalSender {
    /// Serialized ExternalSender containing signature_key and credential.
    pub external_sender: Vec<u8>,
}

/// Key package for DAVE MLS group participation.
///
/// Sent to the server (Opcode 26) during the join handshake.
/// The basic credential identity is the big-endian 64-bit user ID.
///
/// **Note:** This opcode uses binary WebSocket frames, not JSON.
/// Binary format: `[opcode: u8][key_package: Vec<u8>]` (no sequence number)
#[derive(Clone, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct DaveMlsKeyPackage {
    /// Serialized MLSMessage containing the KeyPackage (see RFC 9420).
    pub key_package: Vec<u8>,
}

/// Operation type for MLS proposals.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
#[repr(u8)]
pub enum DaveMlsProposalsOperationType {
    /// Append proposals to the pending proposal list.
    Append = 0,
    /// Revoke previously sent proposals by their reference.
    Revoke = 1,
}

/// Proposals for group member changes.
///
/// Received from the server (Opcode 27) for add/remove operations.
/// Contains either proposals to append or proposal refs to revoke.
///
/// **Note:** This opcode uses binary WebSocket frames, not JSON.
/// Binary format: `[opcode: u8][operation_type: u8][proposals: Vec<u8>]`
#[derive(Clone, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct DaveMlsProposals {
    /// The type of operation (append or revoke).
    pub operation_type: DaveMlsProposalsOperationType,
    /// Serialized proposal data.
    /// For append: serialized MLSMessage proposal messages.
    /// For revoke: serialized ProposalRef values.
    pub proposals: Vec<u8>,
}

/// Commit with optional welcome message for group transitions.
///
/// Sent by the client (Opcode 28) after processing proposals.
/// When at least one add proposal is handled, the welcome message MUST be included.
///
/// **Note:** This opcode uses binary WebSocket frames, not JSON.
/// Binary format: `[opcode: u8][commit: Vec<u8>][welcome: Option<Vec<u8>>]` (no sequence number)
#[derive(Clone, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct DaveMlsCommitWelcome {
    /// Serialized MLS commit message (see RFC 9420 MLSMessage and Commit definitions).
    pub commit: Vec<u8>,
    /// Optional MLS Welcome message for new members (see RFC 9420 Welcome definition).
    /// Required when the commit includes one or more add proposals.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub welcome: Option<Vec<u8>>,
}

/// Welcome message for new members joining the group.
///
/// Received from the server (Opcode 30) as confirmation of successful join.
/// Includes the transition ID for the group transition.
///
/// **Note:** This opcode uses binary WebSocket frames, not JSON.
/// Binary format: `[opcode: u8][transition_id: u16][welcome: Vec<u8>]`
#[derive(Clone, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct DaveMlsWelcome {
    /// The transition ID for this group transition.
    pub transition_id: u16,
    /// Serialized MLS Welcome message (see RFC 9420 Welcome definition).
    pub welcome: Vec<u8>,
}

/// Prepare epoch notification before group transition.
///
/// Received from the server (Opcode 24) to signal an upcoming epoch change.
/// When `epoch` is 1, this indicates a new MLS group is to be created.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct DavePrepareEpoch {
    /// The protocol version for the upcoming epoch.
    pub protocol_version: u16,
    /// The new epoch number after the transition.
    pub epoch: u64,
}

/// Transition ready confirmation.
///
/// Sent by the client (Opcode 23) to confirm it's ready for a previously announced transition.
/// The client sends this after processing a commit or preparing receive-side decryptors.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]
pub struct DaveTransitionReady {
    /// The transition ID the client is ready to execute.
    pub transition_id: u16,
    /// The protocol version for the transition.
    pub protocol_version: u16,
}

/// Prepare protocol transition notification.
///
/// Received from the server (Opcode 21) to announce an upcoming protocol transition.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct DavePrepareTransition {
    /// The protocol version for the transition.
    pub protocol_version: u16,
    /// The transition ID for this transition.
    pub transition_id: u16,
}

/// Execute protocol transition notification.
///
/// Received from the server (Opcode 22) to execute a previously prepared transition.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct DaveExecuteTransition {
    /// The transition ID for this transition.
    pub transition_id: u16,
}

/// Announce commit for group transition.
///
/// Received from the server (Opcode 29) to broadcast an MLS commit for moving to the next epoch.
/// The commit is one received from a group member via dave_mls_commit_welcome (Opcode 28).
///
/// **Note:** This opcode uses binary WebSocket frames, not JSON.
/// Binary format: `[opcode: u8][transition_id: u16][commit_message: Vec<u8>]`
#[derive(Clone, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct DaveMlsAnnounceCommitTransition {
    /// The transition ID for this group epoch change.
    pub transition_id: u16,
    /// Serialized MLS commit message (see RFC 9420 MLSMessage and Commit definitions).
    pub commit_message: Vec<u8>,
}

/// Invalid commit or welcome report.
///
/// Sent to the server (Opcode 31) to report an invalid commit or welcome message.
/// This asks the voice gateway to remove and re-add the member to recover.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Deserialize, Serialize)]
pub struct DaveMlsInvalidCommitWelcome {
    /// The transition ID in which the invalid Commit or Welcome was received.
    pub transition_id: u16,
}
