[package]
name = "08_env_logging"
version = "0.1.0"
authors = ["my name <my@email.address>"]

[dependencies]
env_logger = "~0.4"
log = "~0.3"

[dependencies.serenity]
features = ["client"]
path = "../../"
