[package]
name = "e18_interactions_endpoint"
version = "0.1.0"
authors = ["my name <my@email.address>"]
edition = "2018"

[dependencies]
serenity = { path = "../../", default-features = false, features = ["builder", "interactions_endpoint"] }
tiny_http = "0.12.0"
