[package]
name = "basic-twilight-bot"
version = "0.1.0"
authors = ["Twilight and Serenity Contributors"]
edition = "2018"

[dependencies]
futures = "0.3"
tracing = "0.1"
tracing-subscriber = "0.2"
serde_json = { version = "1" }
tokio = { features = ["macros", "rt-threaded", "sync"], version = "0.2" }
twilight-gateway = "0.1"
twilight-http = "0.1"
twilight-model = "0.1"
twilight-standby = "0.1"

[dependencies.songbird]
path = "../.."
default-features = false
features = ["twilight-rustls", "gateway", "driver", "stock-zlib"]
