[package]
name = "e10_voice_receive"
version = "0.1.0"
authors = ["my name <my@email.address>"]
edition = "2018"

[dependencies]
env_logger = "~0.6"
log = "~0.4"

[dependencies.serenity]
features = ["client", "standard_framework", "voice", "rustls_backend"]
path = "../../"
