name: Labeler

permissions:
  contents: read
  pull-requests: write

on: [pull_request_target]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
